packages:
  - apps/*
  - modules/*
  - libraries/*

catalog:
  '@effect/platform': 0.93.3
  '@eslint/js': 9.39.1
  '@types/node': ^24.9.2
  effect: 3.19.4
  esbuild: ^0.25.11
  eslint: 9.39.1
  eslint-plugin-only-warn: 1.1.0
  rimraf: ^6.0.1
  typescript: 5.9.3
  typescript-eslint: 8.48.1

injectWorkspacePackages: true

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - msgpackr-extract
