#!/bin/sh

# DNDEVOPS_DEPLOYMENT = all,identity,events,game
# DNDEVOPS_IDENTITY_POSTGRES_URI
# DNDEVOPS_EVENTS_POSTGRES_URI
# DNDEVOPS_GAME_POSTGRES_URI

# DNDEVOPS_ADMINS
# DNDEVOPS_SMTP_URI
# DNDEVOPS_SMTP_SENDER
# DNDEVOPS_HTTP_ADDRESS
# DNDEVOPS_HTTP_PORT

DNDEVOPS_RUN_IDENTITY=false
DNDEVOPS_RUN_GAME=false
DNDEVOPS_RUN_EVENTS=false
DNDEVOPS_RUN_FRONTEND=false

case "$DNDEVOPS_DEPLOYMENT" in
  all)
    DNDEVOPS_RUN_IDENTITY=true
    DNDEVOPS_RUN_GAME=true
    DNDEVOPS_RUN_EVENTS=true
    DNDEVOPS_RUN_FRONTEND=true
    ;;
  identity) DNDEVOPS_RUN_IDENTITY=true ;;
  game) DNDEVOPS_RUN_GAME=true ;;
  events) DNDEVOPS_RUN_EVENTS=true ;;
  frontend) DNDEVOPS_RUN_FRONTEND=true ;;
esac


export DNDEVOPS_RUN_IDENTITY
export DNDEVOPS_RUN_GAME
export DNDEVOPS_RUN_EVENTS
export DNDEVOPS_RUN_FRONTEND


exec supervisord --configuration=./supervisord.conf